enable github ci caching (#1577)
Signed-off-by: sir-hassan <yassir.hassan@direktiv.io>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -15,9 +15,45 @@ env:
   IS_GITHUB_ACTIONS: true
 
 jobs:
+  backend-cache:
+    runs-on: ubuntu-latest
+    outputs:
+      hash: ${{ steps.step1.outputs.hash }}
+      cache_hit: ${{ steps.step1.outputs.cache_hit }}
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - id: step1
+        run: |
+          set +e
+          export hash=checksum-${{ hashFiles('cmd', 'pkg', 'go.mod', 'go.sum') }};
+          docker manifest inspect ghcr.io/direktiv/direktiv:$hash;
+          echo "hash=$hash" >> $GITHUB_OUTPUT;
+          echo "cache_hit=$?" >> $GITHUB_OUTPUT;
+
+
+  ui-cache:
+    runs-on: ubuntu-latest
+    outputs:
+      hash: ${{ steps.step1.outputs.hash }}
+      cache_hit: ${{ steps.step1.outputs.cache_hit }}
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - id: step1
+        run: |
+          set +e
+          export hash=checksum-${{ hashFiles('ui') }};
+          docker manifest inspect ghcr.io/direktiv/direktiv-ui:$hash;
+          echo "hash=$hash" >> $GITHUB_OUTPUT;
+          echo "cache_hit=$?" >> $GITHUB_OUTPUT;
+
   backend-license:
     runs-on: ubuntu-latest
-
+    needs: [backend-cache]
+    if: needs.backend-cache.outputs.cache_hit == '1'
     steps:
       - uses: actions/checkout@v4
 
@@ -31,6 +67,8 @@ jobs:
 
   backend-lint:
     runs-on: ubuntu-latest
+    needs: [backend-cache]
+    if: needs.backend-cache.outputs.cache_hit == '1'
 
     steps:
       - uses: actions/checkout@v4
@@ -48,6 +86,8 @@ jobs:
 
   backend-test:
     runs-on: ubuntu-latest
+    needs: [backend-cache]
+    if: needs.backend-cache.outputs.cache_hit == '1'
 
     steps:
       - uses: actions/checkout@v4
@@ -65,8 +105,9 @@ jobs:
           DIREKTIV_APP: flow
 
   backend-build:
-    needs: [ backend-license, backend-lint, backend-test ]
+    needs: [ backend-cache, backend-license, backend-lint, backend-test ]
     runs-on: ubuntu-latest
+    if: needs.backend-cache.outputs.cache_hit == '1'
     permissions:
       contents: read
       packages: write
@@ -90,6 +131,8 @@ jobs:
             type=ref,event=branch
             type=ref,event=pr
             type=sha,format=long
+            type=raw,value=${{ needs.backend-cache.outputs.hash }}
+
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
@@ -119,6 +162,8 @@ jobs:
 
   ui-build:
     runs-on: ubuntu-latest
+    needs: [ui-cache]
+    if: needs.ui-cache.outputs.cache_hit == '1'
     permissions:
       contents: read
       packages: write
@@ -142,6 +187,7 @@ jobs:
             type=ref,event=branch
             type=ref,event=pr
             type=sha,format=long
+            type=raw,value=${{ needs.ui-cache.outputs.hash }}
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
@@ -169,7 +215,8 @@ jobs:
           cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
 
   e2e:
-    needs: [ ui-build, backend-build ]
+    needs: [ ui-cache, ui-build, backend-cache, backend-build ]
+    if: ${{ always() }}
     runs-on: ubuntu-latest
 
     timeout-minutes: 18
@@ -250,12 +297,12 @@ jobs:
           pullPolicy: IfNotPresent
           registry: ghcr.io
           image: direktiv/direktiv
-          tag: sha-${{ github.sha }}
+          tag: ${{ needs.backend-cache.outputs.hash }}
           flow:
             logging: json
           frontend:
             image: direktiv/direktiv-ui
-            tag: sha-${{ github.sha }}
+            tag: ${{ needs.ui-cache.outputs.hash }}
           database:
             host: "$DB_HOST"
             port: $DB_PORT
@@ -288,6 +335,25 @@ jobs:
           echo "API failed to be healthy";
           kubectl get pods;
           kubectl logs deployments/direktiv-flow;
+          exit 1;
+
+      - name: Wait until UI is healthy
+        run: |
+          endpoint="http://${{ env.DIREKTIV_HOST }}";
+          for attempt in {1..20}
+          do
+            status_code=$(curl -s -o /dev/null -w "%{http_code}" $endpoint || true);
+            echo "API status code: $status_code";
+            if [ $status_code -eq 200 ]
+            then
+              echo "UI ready" && exit 0;  
+            fi
+            sleep 1;
+          done
+          
+          echo "UI failed to be healthy";
+          kubectl get pods;
+          kubectl describe po direktiv-frontend;
           exit 1;
 
       - name: Run API E2E tests
