Adds a coverage check into the unit tests CI/CD.
Signed-off-by: Alan Murtagh <alan.murtagh@direktiv.io>

diff --git a/.github/workflows/go-unittests.yml b/.github/workflows/go-unittests.yml
--- a/.github/workflows/go-unittests.yml
+++ b/.github/workflows/go-unittests.yml
@@ -23,5 +23,22 @@ jobs:
       - name: Install dependencies
         run: ./scripts/install-dependencies.sh 
         shell: bash
-      - name: Run check
-        run: make unittest
+      - name: Run unit tests
+        run: |
+            go test ./... -coverprofile coverage.out -covermode count
+            go tool cover -func coverage.out
+      - name: Quality Gate - Test coverage shall be above threshold
+        env:
+            TESTCOVERAGE_THRESHOLD: 1
+        run: |
+              echo "Quality Gate: checking test coverage is above threshold ..."
+              echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
+              totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+              echo "Current test coverage : $totalCoverage %"
+              if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+                  echo "OK"
+              else
+                  echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+                  echo "Failed"
+                  exit 1
+              fi
